import { useEffect, useRef, useState } from 'react';
import { Disc3, Pause, Play, Volume2, VolumeX, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
export interface PlayerTrack { id:string;title:string;artist:string;cover?:string|null;audioUrl?:string }
export function MiniPlayer({track,onClose,onMessage,onPlayed}: {track:PlayerTrack;onClose:()=>void;onMessage:(text:string)=>void;onPlayed:()=>void}) {
 const audio=useRef<HTMLAudioElement>(null);const [playing,setPlaying]=useState(false),[muted,setMuted]=useState(false);
 useEffect(()=>{setPlaying(false);},[track.id]);
 async function toggle(){const el=audio.current;if(!el||!track.audioUrl){onMessage('Esta faixa não tem áudio de prévia disponível.');return;}if(playing){el.pause();setPlaying(false);}else{try{await el.play();setPlaying(true);onPlayed();}catch{setPlaying(false);onMessage('Não foi possível reproduzir esta prévia.');}}}
 return <aside className="mini-player profile-theme" aria-label="Mini player"><audio ref={audio} src={track.audioUrl} muted={muted} onEnded={()=>setPlaying(false)} onPause={()=>setPlaying(false)} onPlay={()=>setPlaying(true)}/><span className="mini-cover">{track.cover?<img src={track.cover} alt=""/>:<Disc3 size={23}/>}</span><div className="mini-track"><strong>{track.title}</strong><span>{track.artist}</span></div><span className="mini-wave" data-playing={playing} aria-hidden="true">{[0,1,2,3].map(i=><i key={i}/>)}</span><Button variant="ghost" size="icon" aria-label={playing?'Pausar':'Reproduzir'} title={track.audioUrl?'Reproduzir prévia':'Sem áudio de prévia'} onClick={toggle}>{playing?<Pause size={18}/>:<Play size={18}/>}</Button><Button variant="ghost" size="icon" aria-label={muted?'Ativar som':'Silenciar'} title={muted?'Ativar som':'Silenciar'} onClick={()=>setMuted(!muted)}>{muted?<VolumeX size={16}/>:<Volume2 size={16}/>}</Button><Button variant="ghost" size="icon" aria-label="Fechar player" title="Fechar player" onClick={onClose}><X size={15}/></Button></aside>;
}