import { useState } from 'react';
import { ArrowUpRight, AudioLines, CalendarPlus, Check, Disc3, Headphones, LockKeyhole, MapPin, Moon, Pencil, Plus, Sparkles, X, Share2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import { lovable } from '@/integrations/lovable';
import { ProfileArt, ART_NAMES } from '@/components/profile-art';
import { ProfileStory } from '@/components/profile-story';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { FREQUENCY_SYMBOLS, MISSIONS, CONCEPT_EVENTS, missionXP, curatorLevel, recentTextures, type Engagement, type MissionId, type TextureTrack } from '@/lib/profile-engagement';
import { badges, calendarFile, dailyFact, localDay, streakDays, weekDays, type Activity, type MusicEvent } from '@/lib/music-profile';
export interface ProfileData { display_name: string; bio: string; avatar: number; activity: Activity[]; events: MusicEvent[] }
export const defaultProfile: ProfileData = { display_name:'Meu perfil', bio:'', avatar:0, activity:[], events:[] };
export interface ProfileLibrary { tracks: ({id:string;sample?:boolean;status?:string;review?:string;createdAt?:string} & TextureTrack)[]; logDays: string[] }
const names=ART_NAMES;
const Avatar=ProfileArt;
export function MusicProfile({profile,onSave,library,onDJ,onHome,signedIn,engagement,onSymbol,onMission}: {profile:ProfileData;onSave:(p:ProfileData)=>Promise<boolean>;library:ProfileLibrary;onDJ:()=>void;onHome:()=>void;signedIn:boolean;engagement:Engagement;onSymbol:(index:number)=>void;onMission:(id:MissionId)=>void}) {
 const [editing,setEditing]=useState(false),[gallery,setGallery]=useState(false),[draft,setDraft]=useState(profile),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[selectedDay,setSelectedDay]=useState<string|null>(null);
 const [event,setEvent]=useState({name:'',date:'',location:''});
 const [symbolsOpen,setSymbolsOpen]=useState(false),[storyOpen,setStoryOpen]=useState(false);
 const xp=missionXP(engagement.completed),level=curatorLevel(xp),symbol=FREQUENCY_SYMBOLS[engagement.symbol]?.emoji??'🍍';
 const now=new Date(),today=localDay(now),days=[...new Set([...library.logDays,...profile.activity.map(a=>a.day)])],streak=streakDays(days,now),unlocked=badges(library.tracks,profile.activity),fact=dailyFact(today);
 const future=profile.events.filter(e=>e.date>=today).sort((a,b)=>a.date.localeCompare(b.date));
 async function save(next:ProfileData) {setBusy(true);const ok=await onSave(next);setBusy(false);setMessage(ok?(signedIn?'Perfil salvo.':'Prévia atualizada. Entre para salvar seu perfil.'):'Não foi possível salvar. Tente novamente.');return ok;}
 async function login(){setBusy(true);const result=await lovable.auth.signInWithOAuth('google',{redirect_uri:window.location.origin});if(result.error)setMessage('Não foi possível entrar. Tente novamente.');setBusy(false);}
 function download(e:MusicEvent){const url=URL.createObjectURL(new Blob([calendarFile(e)],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='music-desk-evento.ics';a.click();URL.revokeObjectURL(url);setMessage('Evento pronto para importar no calendário.');}
 return <div className="music-profile profile-theme">
 <header className="profile-top"><Button variant="ghost" onClick={onHome} aria-label="Music Desk — ir para Diário">MUSIC DESK <span>PRO</span></Button><Button variant="ghost" onClick={()=>setSymbolsOpen(true)} aria-label="Personalizar Símbolo da Frequência"><span>{symbol}</span><b>{streak}</b></Button></header>
 <main className="profile-main">
 <div className="profile-page-title"><div><span className="profile-eyebrow">PESSOAL / 04</span><h1>Perfil musical</h1></div><Button variant="outline" size="sm" onClick={()=>setStoryOpen(true)}><Share2 size={14}/><span>Exportar Cartão</span></Button></div>
 <Button className="profile-dj-entry" variant="ghost" onClick={onDJ}><span className="profile-dj-icon"><Headphones size={24}/></span><span><small>PERFORMANCE WORKSPACE <b>PRO</b></small><strong>Alternar para DJ Desk</strong></span><ArrowUpRight size={24}/></Button>
 <section className="profile-identity" aria-label="Identidade musical"><Button variant="ghost" className="profile-avatar" aria-label="Escolher avatar" onClick={()=>setGallery(!gallery)} aria-expanded={gallery}><Avatar index={profile.avatar}/><span className="profile-avatar-edit"><Pencil size={13}/></span></Button><div className="profile-person"><span className="profile-eyebrow">CURADOR MUSICAL</span><h2>{profile.display_name}</h2><p>{profile.bio||'Sua identidade, na sua frequência.'}</p></div><Button variant="outline" size="sm" onClick={()=>{setDraft(profile);setEditing(!editing);}}><Pencil size={13}/>Editar perfil</Button>
 <div className="profile-level"><div><strong>Nível {String(level.level).padStart(2,'0')}: {level.name}</strong><span>{xp} / {level.next} XP</span></div><progress max={100} value={level.progress} aria-label="Progresso de XP"/></div><div className="profile-stats"><div><strong>{library.tracks.length}</strong><span>Faixas no Diário</span></div><div><strong>{streak}</strong><span>Dias de Ofensiva</span></div><div><strong>{library.tracks.filter(t=>t.status==='repeat').length}</strong><span>Favoritas</span></div></div></section>
 {gallery&&<section className="profile-gallery" aria-label="Galeria de avatares"><div className="profile-section-heading"><h3>Escolha sua frequência</h3><Button size="icon" variant="ghost" aria-label="Fechar galeria" onClick={()=>setGallery(false)}><X/></Button></div><div className="profile-avatar-grid">{names.map((name,i)=><Button key={name} variant="ghost" className="profile-avatar-option" aria-label={`Avatar ${name}`} aria-pressed={profile.avatar===i} disabled={busy} onClick={async()=>{if(await save({...profile,avatar:i}))setGallery(false);}}><Avatar index={i}/><span>{name}</span>{profile.avatar===i&&<Check size={16}/>}</Button>)}</div></section>}
 {editing&&<form className="profile-form" onSubmit={async e=>{e.preventDefault();if(await save(draft))setEditing(false);}}><label>Nome do curador<input required maxLength={60} value={draft.display_name} onChange={e=>setDraft({...draft,display_name:e.target.value})}/></label><label>Bio<textarea maxLength={180} value={draft.bio} onChange={e=>setDraft({...draft,bio:e.target.value})}/></label><div><Button disabled={busy} type="submit">{busy?'Salvando…':'Salvar perfil'}</Button><Button variant="ghost" type="button" onClick={()=>setEditing(false)}>Cancelar</Button></div></form>}
 {!signedIn&&<div className="profile-signin"><span>Seu perfil, guardado com você.</span><Button variant="outline" size="sm" disabled={busy} onClick={login}>Entrar com Google <ArrowUpRight size={14}/></Button></div>}
 {message&&<p className="profile-feedback" role="status">{message}</p>}
 <div className="profile-columns"><div>
 <section className="profile-habits"><div className="profile-section-heading"><h2>Sua frequência</h2><span>ESTA SEMANA</span></div><div className="profile-streak"><Button variant="ghost" className="profile-flame" aria-label="Personalizar Símbolo da Frequência" onClick={()=>setSymbolsOpen(true)}>{symbol}</Button><strong>{streak}</strong><div><h3>{streak===1?'dia de ofensiva':'dias de ofensiva'}</h3><p>Uma boa escuta puxa a próxima.</p></div><Button variant="ghost" size="icon" title="Personalizar símbolo" aria-label="Alterar símbolo" onClick={()=>setSymbolsOpen(true)}><Pencil size={13}/></Button></div><div className="profile-week">{weekDays(now).map((day,i)=><Button variant="ghost" key={day} className="profile-day" data-complete={days.includes(day)} data-today={day===today} aria-pressed={selectedDay===day} aria-label={`${day}: ${days.includes(day)?'completado':'sem registro'}`} onClick={()=>setSelectedDay(selectedDay===day?null:day)}><span>{['SEG','TER','QUA','QUI','SEX','SÁB','DOM'][i]}</span><i>{days.includes(day)?<Check size={16}/>:Number(day.slice(-2))}</i></Button>)}</div>{selectedDay&&<p className="profile-day-note">{new Date(`${selectedDay}T12:00:00`).toLocaleDateString('pt-BR',{day:'numeric',month:'long'})} · {days.includes(selectedDay)?'Atividade musical registrada':'Nenhuma atividade registrada'}</p>}</section>
 <section className="profile-missions"><div className="profile-section-heading"><h2>Desafios Ativos</h2><span>{engagement.completed.length} / 4</span></div>{MISSIONS.map(m=><label className="profile-mission" key={m.id} data-done={engagement.completed.includes(m.id)}><Checkbox checked={engagement.completed.includes(m.id)} disabled={engagement.completed.includes(m.id)} onCheckedChange={checked=>{if(checked===true)onMission(m.id);}}/><span>{m.label}</span><b>+{m.xp} XP</b></label>)}</section>
 <section className="profile-achievements"><div className="profile-section-heading"><h2>Pequenas grandes conquistas</h2><span>{unlocked.filter(Boolean).length} / 3</span></div><div className="profile-badges">{[{name:'Primeiro Garimpo',hint:'Registre sua primeira faixa.',Icon:Disc3},{name:'Colecionador Noturno',hint:'Explore ou registre uma faixa entre 22h e 5h.',Icon:Moon},{name:'Ouvinte Imersivo',hint:'Escreva uma micro-review para uma faixa.',Icon:Headphones}].map(({name,hint,Icon},i)=><div className="profile-badge" data-unlocked={unlocked[i]} key={name} title={hint}><span><Icon size={25}/>{!unlocked[i]&&<LockKeyhole size={10}/>}</span><h3>{name}</h3><p>{unlocked[i]?'Desbloqueado':hint}</p></div>)}</div></section>
 </div><section className="profile-fact"><div className="profile-section-heading"><span><Sparkles size={14}/> PÍLULA DO DIA</span><span>{now.toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</span></div><span className="profile-eyebrow">{fact.category}</span><h2>{fact.title}</h2><p>{fact.text}</p><a href={fact.url} target="_blank" rel="noreferrer">{fact.source}<ArrowUpRight size={14}/></a><div className="profile-fact-lines" aria-hidden="true">{Array.from({length:24},(_,i)=><i key={i}/>)}</div></section></div>
 <section className="profile-events"><div className="profile-section-heading"><div><span className="profile-eyebrow">FORA DOS FONES</span><h2>Shows próximos</h2></div><Button variant="outline" size="sm" onClick={()=>setAdding(!adding)}><Plus size={14}/>Adicionar ao radar</Button></div>
 <p className="profile-event-disclaimer">Encontros conceituais · links gerais das plataformas, não ingressos confirmados.</p><div className="profile-event-list conceptual-events">{CONCEPT_EVENTS.map(e=><article className="profile-event" key={e.id}><time dateTime={e.date}><span>{new Date(`${e.date}T12:00:00`).toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}</span><strong>{Number(e.date.slice(-2))}</strong></time><div><h3>{e.name}</h3><p><MapPin size={13}/>{e.location}</p><div className="event-tags"><span>{e.tag}</span><b>{e.price}</b></div></div><Button variant="outline" size="sm" asChild><a href={e.url} target="_blank" rel="noopener noreferrer">Garantir Entrada<ArrowUpRight size={13}/></a></Button></article>)}</div>
 {adding&&<form className="profile-form profile-event-form" onSubmit={async e=>{e.preventDefault();if(await save({...profile,events:[...profile.events,{...event,id:crypto.randomUUID()}]})){setAdding(false);setEvent({name:'',date:'',location:''});}}}><label>Evento / artista<input required maxLength={120} value={event.name} onChange={e=>setEvent({...event,name:e.target.value})}/></label><label>Data<input type="date" required min={today} value={event.date} onChange={e=>setEvent({...event,date:e.target.value})}/></label><label>Cidade / local<input required maxLength={160} value={event.location} onChange={e=>setEvent({...event,location:e.target.value})}/></label><Button type="submit" disabled={busy}>Adicionar evento</Button></form>}
 <div className="profile-event-list">{future.map(e=><article className="profile-event" key={e.id}><time dateTime={e.date}><span>{new Date(`${e.date}T12:00:00`).toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}</span><strong>{Number(e.date.slice(-2))}</strong></time><div><h3>{e.name}</h3><p><MapPin size={13}/>{e.location}</p></div><Button variant="ghost" size="sm" onClick={()=>download(e)}><CalendarPlus size={16}/><span>Salvar no Calendário</span></Button><Button variant="ghost" size="icon" aria-label={`Remover ${e.name}`} disabled={busy} onClick={()=>save({...profile,events:profile.events.filter(item=>item.id!==e.id)})}><X size={14}/></Button></article>)}</div>{!future.length&&<div className="profile-events-empty"><CalendarPlus size={25}/><h3>Nenhum show no radar, por enquanto.</h3><p>A próxima boa noite ainda está por vir.</p></div>}</section>
 <footer className="profile-footer"><AudioLines size={16}/> A música também conta quem você é.</footer>
 <Dialog open={symbolsOpen} onOpenChange={setSymbolsOpen}><DialogContent className="profile-theme profile-modal"><DialogTitle>Personalizar Símbolo da Frequência</DialogTitle><DialogDescription>Sua frequência, seu símbolo.</DialogDescription><div className="symbol-grid">{FREQUENCY_SYMBOLS.map((s,i)=><Button variant="ghost" key={s.name} aria-pressed={engagement.symbol===i} onClick={()=>{onSymbol(i);setSymbolsOpen(false);}}><span>{s.emoji}</span><small>{s.name}</small></Button>)}</div></DialogContent></Dialog>
 <ProfileStory open={storyOpen} onOpenChange={setStoryOpen} name={profile.display_name} avatar={profile.avatar} streak={streak} symbol={symbol} xp={xp} tags={recentTextures(library.tracks)}/>
 </main></div>;
}
